# Generated by Django 3.2 on 2022-04-11 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_auto_20220410_1344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='grupo.grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='propietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariopersonalizado'),
            preserve_default=False,
        ),
    ]
