# Generated by Django 3.2 on 2022-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_auto_20220410_1344'),
        ('chat', '0009_alter_mensaje_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='grupo',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='grupo',
            field=models.ManyToManyField(to='grupo.Grupo'),
        ),
    ]
