# Generated by Django 3.2 on 2022-04-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_auto_20220410_1344'),
        ('chat', '0010_auto_20220415_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='grupo',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo'),
        ),
    ]
