# Generated by Django 3.2 on 2022-04-15 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0012_alter_mensaje_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariopersonalizado'),
        ),
    ]
