# Generated by Django 3.2 on 2022-04-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='ap_materno',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='ap_paterno',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
