# Generated by Django 3.2 on 2022-04-10 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='descripcion',
            field=models.CharField(default='Sin descripcion', max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
