# Generated by Django 3.2 on 2022-05-01 18:36

from django.db import migrations, models
import django.db.models.deletion
from dbview.helpers import CreateView


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_auto_20220410_1344'),
    ]

    operations = [
        CreateView(
            name='MiVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.ForeignKey(db_column='pk', on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
