# Generated by Django 3.2 on 2022-05-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0003_mivista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mivista',
            name='propietario',
            field=models.ForeignKey(db_column='propietario', on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo'),
        ),
    ]
