# Generated by Django 3.2 on 2022-05-01 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupo', '0004_alter_mivista_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mivista',
            name='propietario',
            field=models.ForeignKey(db_column='propietario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
