# Generated by Django 3.2 on 2022-05-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0005_alter_mivista_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mivista',
            name='propietario',
        ),
        migrations.AddField(
            model_name='mivista',
            name='grupo',
            field=models.ForeignKey(db_column='grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo'),
        ),
    ]
