# Generated by Django 3.2 on 2022-05-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0006_auto_20220501_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mivista',
            name='grupo',
            field=models.ForeignKey(db_column='grupo_pr', null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo'),
        ),
    ]
