# Generated by Django 3.2 on 2022-05-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0007_alter_mivista_grupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mivista',
            options={'managed': False},
        ),
    ]
